version: 2.1
jobs:
  house_keeping:
    parameters:
      img:
        type: string
    docker: 
      - image: svalinn/dagmc-ci-ubuntu-<< parameters.img >>:latest
    working_directory: /root/build/gcc/DAGMC-moab-5.1.0-hdf5-1.10.4/DAGMC
    steps:
      - checkout
      - run:
          name: Setup enviroment
          command: |
            echo "export COMPILER=gcc" >> $BASH_ENV
            echo "export MOAB_VERSION=5.1.0" >> $BASH_ENV
            echo "export HDF5_VERSION=1.10.4" >> $BASH_ENV
            echo "export TRAVIS_REPO_SLUG=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PR_REPONAME}" >> $BASH_ENV
            echo "export TRAVIS_PULL_REQUEST=${CIRCLE_PR_NUMBER}" >> $BASH_ENV
      - run:
          name: Housekeeping
          command: CI/travis/housekeeping.sh
 
  build_and_test:
    parameters:
      img:
        type: string
      compiler:
        type: string
      hdf5:
        type: string
      moab: 
        type: string
    docker: 
      - image: svalinn/dagmc-ci-ubuntu-<< parameters.img >>:latest
    working_directory: /root/build/<< parameters.compiler >>/DAGMC-moab-<< parameters.moab >>-hdf5-<< parameters.hdf5 >>/DAGMC
    steps:
      - checkout
      - run:
          name: Setup enviroment
          command: |
            echo "export COMPILER=<< parameters.compiler >>" >> $BASH_ENV
            echo "export MOAB_VERSION=<< parameters.moab >>" >> $BASH_ENV
            echo "export HDF5_VERSION=<< parameters.hdf5 >>" >> $BASH_ENV
            echo "export TRAVIS_REPO_SLUG=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PR_REPONAME}" >> $BASH_ENV
            echo "export TRAVIS_PULL_REQUEST=${CIRCLE_PR_NUMBER}" >> $BASH_ENV
      - run:
          name: building DAGMC
          command: CI/travis/install.sh
      - run:
          name: building DAGMC
          command: CI/travis/tests.sh
  

workflows:
  version: 2
  pull_request:
    jobs:
      - house_keeping:
          matrix:
            parameters:
              img: ["18.04"]
          filters:
            branches:
              ignore: develop
      
      - build_and_test:
          matrix:
            parameters:
              img: [ "16.04", "18.04"]
              compiler: ["clang", "gcc"]
              hdf5: ["1.10.4"]
              moab: ["5.1.0"]
          filters:
            branches:
              ignore: develop
    