name: Standard Build and Test

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      hdf5_versions: ${{ matrix.hdf5_versions }}
      hdf5_build_dir: hdf5_build_dir

    strategy:
      matrix:
       ubuntu_versions : [
          16.04,
          18.04,
          ]
       compiler : [
          gcc,
          clang,
          ]
       hdf5_versions : [
         1.10.4,
       ]
       moab_versions : [
         9c96d17,
         develop,
         master,
       ]

    container:
      image: svalinn/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler }}-ext-hdf5_${{ matrix.hdf5_versions }}-moab_${{ matrix.moab_versions }}:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup
        run: |
          mkdir /root/build_dir/DAGMC
          export MOAB_VERSION=${{ matrix.moab_versions }}
          export COMPILER=${{ matrix.compiler }}
          export HDF5_VERSION=${{ matrix.hdf5_versions }}
          export REPO_SLUG=${GITHUB_REPOSITORY}
          export PULL_REQUEST=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          export DOUBLE_DOWN="OFF"
          echo  $GITHUB_REF | cut -d"/" -f3
      - name: Building DAGMC
        run: |
          CI/circleci/install.sh