name: Standard Build and Test

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      hdf5_versions: ${{ matrix.hdf5_versions }}
      hdf5_build_dir: hdf5_build_dir

    strategy:
      matrix:
       ubuntu_versions : [
          16.04,
          18.04,
          ]
       compiler : [
          gcc,
          clang,
          ]
       hdf5_versions : [
         1.10.4,
       ]
       moab_versions : [
         9c96d17,
         develop,
         master,
       ]

    container:
      image: svalinn/dagmc-ci-ubuntu-<< parameters.img >>-<< parameters.compiler >>-ext-hdf5_<< parameters.hdf5 >>-moab_<< parameters.moab >>:latest
    
    steps:
      - name: Building DAGMC
        run: CI/circleci/install.sh