name: Build & Publish docker image for DAGMC-CI

on:
  # allows us to run workflows manually
  workflow_dispatch:
  push:
    paths:
      - 'CI/Dockerfile'
      - '.github/workflows/docker_publish.yml'

jobs:
  build-test-dagmc-img:
    needs: [build-moab-img]
    runs-on: ubuntu-latest
    env:
      hdf5_versions: 1.10.4
      hdf5_build_dir: hdf5_build_dir

    strategy:
      matrix:
        ubuntu_versions : [
          18.04,
          20.04,
          ]
        compiler : [
          gcc,
          clang,
          ]
        hdf5_versions : [
         1.10.4,
        ]
        moab_versions : [
         5.3.0,
         develop,
         master,
        ]
        static_exe : [
         OFF,
         ON,
        ]

    name: Installing DAGMC
    steps:        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install DAGMC in Docker image
        uses: docker/build-push-action@v3
        with:
          file: CI/Dockerfile
          target: dagmc
          context: .
          push: false
          build-args: |
            OWNER=${{ github.repository_owner }}
            TAG=ci_testing
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
            HDF5=${{ matrix.hdf5_versions }}
            MOAB=${{ matrix.moab_versions }}
            build_mw_reg_tests=ON
          tags: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}-dagmc:ci_testing

      - name: Test DAGMC in Docker image
        uses: docker/build-push-action@v3
        with:
          file: CI/Dockerfile
          target: dagmc_test
          context: .
          push: false
          build-args: |
            OWNER=${{ github.repository_owner }}
            TAG=ci_testing
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
            HDF5=${{ matrix.hdf5_versions }}
            MOAB=${{ matrix.moab_versions }}
            build_mw_reg_tests=ON
          tags: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}-dagmc-test:ci_testing

      - name: Set up QEMU
        if: ${{ github.repository_owner == 'svalinn' }}
        uses: docker/setup-qemu-action@v2

      - name: Log in to the Container registry
        if: ${{ github.repository_owner == 'svalinn' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image as stable img
        if: ${{ github.repository_owner == 'svalinn' }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}:ci_testing
          dst: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}:stable

      - name: Push Image as latest img
        if: ${{ github.repository_owner == 'svalinn' }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}:ci_testing
          dst: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}:latest
