name: Build & Publish docker image for DAGMC-CI

on:
  push:
    paths:
      - 'CI/*'
      - '.github/workflows/docker_publish.yml'


jobs:
  build-base-img:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_versions : [
          18.04,
          20.04,
          ]
    name: Ubuntu ${{ matrix.ubuntu_versions }} basics deps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Export Dockerfile_0_base
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_0_base
          push: true
          context: .
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
          tags: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}

  build-housekeeping-img:
    needs: build-base-img
    runs-on: ubuntu-latest
    env:
      hdf5_versions: 1.10.4
      hdf5_build_dir: hdf5_build_dir
    strategy:
      matrix:
        ubuntu_versions : [18.04,]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Dockerfile_1_housekeeping
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_1_housekeeping
          context: .
          push: true
          build-args: |
            OWNER=${{ github.repository_owner }}
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
          tags: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-housekeeping


  build-deps-img:
    needs: build-base-img
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_versions : [
          18.04,
          20.04,
          ]
        compiler : [
          gcc,
          clang,
          ]
        hdf5_versions : [
          1.10.4,
        ]

    name: Ubuntu ${{ matrix.ubuntu_versions }} + ${{ matrix.compiler }} hdf5 ${{ matrix.hdf5_versions }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Dockerfile_1_external_deps
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_1_external_deps
          context: .
          push: false
          build-args: |
            OWNER=${{ github.repository_owner }}
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
          tags: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext

      - name: Build and export Dockerfile_2_hdf5
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_2_hdf5
          context: .
          push: true
          build-args: |
            OWNER=${{ github.repository_owner }}
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
            HDF5=${{ matrix.hdf5_versions }}
          tags: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}

  build-moab-img:
    needs: build-deps-img
    runs-on: ubuntu-latest
    env:
      hdf5_versions: 1.10.4
      hdf5_build_dir: hdf5_build_dir
    strategy:
      matrix:
        ubuntu_versions : [
          18.04,
          20.04,
          ]
        compiler : [
          gcc,
          clang,
          ]
        hdf5_versions : [
          1.10.4,
        ]
        moab_versions : [
          9c96d17,
          develop,
          master,
        ]

    name: Ubuntu ${{ matrix.ubuntu_versions }} + ${{ matrix.compiler }} hdf5 ${{ matrix.hdf5_versions }} + Moab ${{ matrix.moab_versions }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Dockerfile_3_moab
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_3_moab
          context: .
          push: true
          build-args: |
            OWNER=${{ github.repository_owner }}
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
            HDF5=${{ matrix.hdf5_versions }}
            MOAB=${{ matrix.moab_versions }}
          tags: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}

  housekeeping:
    needs: [build-housekeeping-img]
    runs-on: ubuntu-latest
    env:
      hdf5_versions: 1.10.4
      hdf5_build_dir: hdf5_build_dir    
    strategy:
      matrix:
        ubuntu_versions : [18.04,]
    container: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-housekeeping:latest

    name: Running Housekeeping scrips
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        run: |
          mkdir /root/build_dir/
          echo "REPO_SLUG=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          echo "PULL_REQUEST=$(echo  $GITHUB_REF | cut -d"/" -f3)" >> $GITHUB_ENV
          ln -s $GITHUB_WORKSPACE /root/build_dir/DAGMC

      - name: Run Housekeeping
        run: |
          cd $GITHUB_WORKSPACE
          /bin/bash "CI/scripts/housekeeping.sh"
      
  test_img:
    # if: ${{ contains(github.event_name, 'pull_request') }}
    needs: [build-moab-img]
    runs-on: ubuntu-latest
    env:
      hdf5_versions: 1.10.4
      hdf5_build_dir: hdf5_build_dir

    strategy:
      matrix:
        ubuntu_versions : [
          18.04,
          20.04,
          ]
        compiler : [
          gcc,
          clang,
          ]
        hdf5_versions : [
         1.10.4,
        ]
        moab_versions : [
         9c96d17,
         develop,
         master,
        ]
    container: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}:latest

    name: Installing and Testing DAGMC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        run: |
          echo "MOAB_VERSION=${{ matrix.moab_versions }}" >> $GITHUB_ENV
          echo "COMPILER=${{ matrix.compiler }}" >> $GITHUB_ENV
          echo "HDF5_VERSION=${{ matrix.hdf5_versions }}" >> $GITHUB_ENV
          echo "REPO_SLUG=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          echo "PULL_REQUEST=$(echo  $GITHUB_REF | cut -d"/" -f3)" >> $GITHUB_ENV
          echo "DOUBLE_DOWN="OFF"" >> $GITHUB_ENV
          ln -s $GITHUB_WORKSPACE /root/build_dir/DAGMC

      - name: Install DAGMC
        run: |
          cd $GITHUB_WORKSPACE
          /bin/bash "CI/scripts/install.sh"

      - name: Run DAGMC Test
        run: |
          cd $GITHUB_WORKSPACE
          /bin/bash "CI/scripts/tests.sh"

  pushing_housekeeping_stable_img:
    # if: ${{ github.repository_owner == 'svalinn' }}
    needs: [housekeeping, test_img]
    runs-on: ubuntu-latest
    env:
      hdf5_versions: 1.10.4
      hdf5_build_dir: hdf5_build_dir
    strategy:
      matrix:
        ubuntu_versions : [18.04,]

    name: Housekeeping':' latest -> stable
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image to stable img
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-housekeeping:latest
          dst: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-housekeeping:stable

  pushing_test_stable_img:
    if: ${{ github.repository_owner == 'svalinn' }}
    needs: [housekeeping, test_img]
    runs-on: ubuntu-latest
    env:
      hdf5_versions: 1.10.4
      hdf5_build_dir: hdf5_build_dir

    strategy:
      matrix:
        ubuntu_versions : [
          18.04,
          20.04,
          ]
        compiler : [
          gcc,
          clang,
          ]
        hdf5_versions : [
         1.10.4,
        ]
        moab_versions : [
         9c96d17,
         develop,
         master,
        ]

    name: U${{ matrix.ubuntu_versions }} + ${{ matrix.compiler }} hdf5 ${{ matrix.hdf5_versions }} + Moab ${{ matrix.moab_versions }}':' latest -> stable

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image to stable img
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}:latest
          dst: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}:stable
