name: Test against MOAB master on PR merge

on:
  # allows us to run workflows manually
  workflow_dispatch:

jobs:
  build-dependency-img:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_versions : [
          22.04,
          ]
        compiler : [
          gcc,
          ]
        hdf5_versions : [
         1.10.4,
        ]
        moab_versions : [
         master,
        ]

    name: Installing Dependencies
    steps:
      - name: default environment
        run: |
          echo "tag-latest-on-default=false" >> "$GITHUB_ENV"

      - name: condition on trigger parameters
        if: ${{ github.repository_owner == 'svalinn' && github.ref == 'refs/heads/develop' }}
        run: |
          echo "tag-latest-on-default=true" >> "$GITHUB_ENV"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing Dependencies in Docker image
        uses: firehed/multistage-docker-build-action@v1
        with:
          repository: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}
          stages: base, external_deps, hdf5
          server-stage: moab
          quiet: false
          parallel: true
          tag-latest-on-default: ${{ env.tag-latest-on-default }}
          dockerfile: CI/Dockerfile
          build-args: COMPILER=${{ matrix.compiler }}, UBUNTU_VERSION=${{ matrix.ubuntu_versions }}, HDF5=${{ matrix.hdf5_versions }}, MOAB=${{ matrix.moab_versions }}

  build-dagmc_test-img:
    needs: [build-dependency-img]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_versions : [
          22.04,
          ]
        compiler : [
          gcc,
          ]
        hdf5_versions : [
         1.10.4,
        ]
        moab_versions : [
         master,
        ]

    name: Installing DAGMC
    steps:        
      - name: default environment
        run: |
          echo "tag-latest-on-default=false" >> "$GITHUB_ENV"

      - name: condition on trigger parameters
        if: ${{ github.repository_owner == 'svalinn' && github.ref == 'refs/heads/develop' }}
        run: |
          echo "tag-latest-on-default=true" >> "$GITHUB_ENV"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build & test DAGMC in Docker image
        uses: firehed/multistage-docker-build-action@v1
        with:
          repository: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler }}-ext-hdf5_${{ matrix.hdf5_versions }}-moab_${{ matrix.moab_versions }}
          stages: moab, dagmc
          server-stage: dagmc_test
          quiet: false
          parallel: true
          tag-latest-on-default: ${{ env.tag-latest-on-default }}
          dockerfile: CI/Dockerfile
          build-args: COMPILER=${{ matrix.compiler }}, UBUNTU_VERSION=${{ matrix.ubuntu_versions }}, HDF5=${{ matrix.hdf5_versions }}, MOAB=${{ matrix.moab_versions }}

  push_stable_ci_img:
    needs: [build-dagmc_test-img]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_versions : [
          22.04,
          ]
        compiler : [
          gcc,
          ]
        hdf5_versions : [
         1.10.4,
        ]
        moab_versions : [
         master,
        ]

    name: Pushing final images
    steps:       
      - name: Log in to the Container registry
        if: ${{ github.repository_owner == 'svalinn' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image as latest img
        if: ${{ github.repository_owner == 'svalinn' && github.ref == 'refs/heads/develop' }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler }}-ext-hdf5_${{ matrix.hdf5_versions }}-moab_${{ matrix.moab_versions }}/dagmc:latest
          dst: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}:latest

      - name: Push Image as latest img
        if: ${{ github.repository_owner == 'svalinn' && github.ref == 'refs/heads/develop' }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler }}-ext-hdf5_${{ matrix.hdf5_versions }}-moab_${{ matrix.moab_versions }}:latest
          dst: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}:stable
